name: Platform IO CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install PlatformIO
        working-directory: ./code
        run: python -m pip install platformio
      - name: Build firmware
        working-directory: ./code
        run: platformio run
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: firmware.bin
          path: code/.pio/build/*/firmware.bin
